package com.cecoel.proves;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DependenciesDuplicades {
	
	
	public static void main(String[] args) {

		List<JarFile> list = new ArrayList<>();
		for (String dependency : libs) {
			list.add(new JarFile(dependency));
		}
		System.out.println("---------------------------------------");
		Map<String, List<String>> map = new HashMap<>();
		for (JarFile jarFile : list) {
			/*
			if (jarFile.getVersion() == null) {
				System.out.println("**** " + jarFile);
			} else {
				System.out.println(jarFile);
			}
			*/
			
			List<String> versions = map.get(jarFile.getName());
			if (versions == null) {
				versions = new ArrayList<String>();
				versions.add(jarFile.getVersion());
				map.put(jarFile.getName(), versions);
				
			} else {
				versions.add(jarFile.getVersion());
			}
		}
		
		for (Map.Entry<String, List<String>> pair : map.entrySet()) {
		    
			if (pair.getValue().size() > 1) {
				System.out.println(pair.getKey() + ": " + pair.getValue());
			}
		}
	}
	
	
	
			
	
	private static String[] libs = new String[] {
		"activation-1.1.jar",
		"ant-1.7.1.jar",
		"ant-launcher-1.7.1.jar",
		"antlr-2.7.7.jar",
		"aopalliance-1.0.jar",
		"apache-log4j-extras-1.2.17.jar",
		"aspectjrt-1.8.1.jar",
		"aspectjweaver-1.8.1.jar",
		"atmosphere-runtime-2.4.30.vaadin7.jar",
		"avalon-framework-impl-4.2.0.jar",
		"backport-util-concurrent-3.1.jar",
		"barcode4j-2.1.jar",
		"batik-anim-1.8.jar",
		"batik-awt-util-1.8.jar",
		"batik-bridge-1.8.jar",
		"batik-css-1.8.jar",
		"batik-dom-1.8.jar",
		"batik-ext-1.8.jar",
		"batik-gvt-1.8.jar",
		"batik-parser-1.8.jar",
		"batik-script-1.8.jar",
		"batik-svg-dom-1.8.jar",
		"batik-util-1.8.jar",
		"batik-xml-1.8.jar",
		"bcmail-jdk14-1.38.jar",
		"bcmail-jdk14-138.jar",
		"bcpkix-jdk18on-1.76.jar",
		"bcprov-jdk14-1.38.jar",
		"bcprov-jdk14-138.jar",
		"bcprov-jdk15on-1.68.jar",
		"bcprov-jdk18on-1.76.jar",
		"bctsp-jdk14-1.38.jar",
		"bcutil-jdk18on-1.76.jar",
		"castor-core-1.3.3.jar",
		"castor-xml-1.3.3.jar",
		"classmate-0.5.4.jar",
		"com.ibm.jbatch-tck-spi-1.0.jar",
		"commons-beanutils-1.9.0.jar",
		"commons-cli-1.0.jar",
		"commons-codec-1.10.jar",
		"commons-codec-1.15.jar",
		"commons-codec-1.6.jar",
		"commons-collections-3.2.1.jar",
		"commons-collections4-4.1.jar",
		"commons-collections4-4.4.jar",
		"commons-dbcp-1.4.jar",
		"commons-digester-2.1.jar",
		"commons-fileupload-1.3.1.jar",
		"commons-fileupload-1.4.jar",
		"commons-io-2.2.jar",
		"commons-io-2.4.jar",
		"commons-lang-2.3.jar",
		"commons-lang-2.6.jar",
		"commons-lang3-3.14.0.jar",
		"commons-lang3-3.4.jar",
		"commons-logging-1.1.1.jar",
		"commons-logging-1.2.jar",
		"commons-net-3.6.jar",
		"commons-pool-1.5.4.jar",
		"commons-validator-1.7.jar",
		"core-2.3.0.jar",
		"core-3.3.0.jar",
		"curvesapi-1.04.jar",
		"dom4j-1.6.1.jar",
		"dss-alert-6.0.jar",
		"dss-asic-cades-6.0.jar",
		"dss-asic-common-6.0.jar",
		"dss-asic-xades-6.0.jar",
		"dss-cades-6.0.jar",
		"dss-common-remote-converter-6.0.jar",
		"dss-common-remote-dto-6.0.jar",
		"dss-crl-parser-6.0.jar",
		"dss-detailed-report-jaxb-6.0.jar",
		"dss-diagnostic-jaxb-6.0.jar",
		"dss-document-6.0.jar",
		"dss-enumerations-6.0.jar",
		"dss-i18n-6.0.jar",
		"dss-jades-6.0.jar",
		"dss-jaxb-common-6.0.jar",
		"dss-jaxb-parsers-6.0.jar",
		"dss-model-6.0.jar",
		"dss-pades-6.0.jar",
		"dss-policy-jaxb-6.0.jar",
		"dss-service-6.0.jar",
		"dss-signature-dto-6.0.jar",
		"dss-signature-remote-6.0.jar",
		"dss-simple-certificate-report-jaxb-6.0.jar",
		"dss-simple-report-jaxb-6.0.jar",
		"dss-spi-6.0.jar",
		"dss-token-6.0.jar",
		"dss-utils-6.0.jar",
		"dss-utils-apache-commons-6.0.jar",
		"dss-xades-6.0.jar",
		"dss-xml-common-6.0.jar",
		"dss-xml-utils-6.0.jar",
		"ecj-4.3.1.jar",
		"ehcache-core-2.4.3.jar",
		"everit-json-schema-1.14.3.jar",
		"ews-java-api-2.0.jar",
		"fixedformat4j-1.2.2.jar",
		"flute-1.3.0.gg2.jar",
		"fontbox-2.0.4.jar",
		"fr.opensagres.xdocreport.converter-2.0.0.jar",
		"fr.opensagres.xdocreport.core-2.0.0.jar",
		"fr.opensagres.xdocreport.document-2.0.0.jar",
		"fr.opensagres.xdocreport.document.docx-2.0.0.jar",
		"fr.opensagres.xdocreport.template-2.0.0.jar",
		"fr.opensagres.xdocreport.template.freemarker-2.0.0.jar",
		"freemarker-2.3.20.jar",
		"gentyref-1.2.0.vaadin1.jar",
		"google-maps-services-0.1.11.jar",
		"gson-2.6.1.jar",
		"gwt-elemental-2.8.2.vaadin2.jar",
		"gwt-elemental-2.9.0.jar",
		"gwt-user-2.9.0.jar",
		"handy-uri-templates-2.1.8.jar",
		"hibernate-commons-annotations-4.0.1.Final.jar",
		"hibernate-core-4.0.0.Final.jar",
		"hibernate-ehcache-4.0.0.Final.jar",
		"hibernate-entitymanager-4.0.0.Final.jar",
		"hibernate-jpa-2.0-api-1.0.1.Final.jar",
		"hibernate-validator-4.0.0.GA.jar",
		"httpclient-4.4.1.jar",
		"httpclient5-5.3.jar",
		"httpcore-4.4.1.jar",
		"httpcore5-5.2.4.jar",
		"httpcore5-h2-5.2.4.jar",
		"iban4j-3.2.0.jar",
		"ical4j-1.0.4.jar",
		"icu4j-57.1.jar",
		"istack-commons-runtime-4.0.1.jar",
		"itext-2.1.7.js5.jar",
		"jackson-annotations-2.9.2.jar",
		"jackson-core-2.9.2.jar",
		"jackson-core-asl-1.9.13.jar",
		"jackson-databind-2.9.2.jar",
		"jackson-dataformat-csv-2.9.2.jar",
		"jackson-datatype-joda-2.1.5.jar",
		"jackson-jaxrs-base-2.9.2.jar",
		"jackson-jaxrs-json-provider-2.9.2.jar",
		"jackson-mapper-asl-1.9.13.jar",
		"jackson-module-jaxb-annotations-2.9.2.jar",
		"jai-core-1.1.3.jar",
		"jai-imageio-core-1.3.1.jar",
		"jai_codec-1.1.3.jar",
		"jakarta-regexp-1.4.jar",
		"jakarta.activation-2.0.1.jar",
		"jakarta.xml.bind-api-3.0.1.jar",
		"jandex-1.0.3.Final.jar",
		"jasperreports-6.3.0.jar",
		"jasperreports-fonts-6.0.0.jar",
		"jasperreports-functions-6.3.0.jar",
		"java-jwt-3.4.1.jar",
		"javase-3.3.0.jar",
		"javassist-3.12.1.GA.jar",
		"javassist-3.30.2-GA.jar",
		"javax.annotation-api-1.3.1.jar",
		"javax.batch-api-1.0.jar",
		"javax.inject-1.jar",
		"javax.mail-1.5.4.jar",
		"jaxb-api-2.1.jar",
		"jaxb-core-3.0.2.jar",
		"jaxb-impl-2.1.3.jar",
		"jaxb-runtime-3.0.2.jar",
		"jaxen-1.1-beta-6.jar",
		"jbig2-imageio-3.0.4.jar",
		"jboss-logging-3.1.0.CR2.jar",
		"jboss-transaction-api_1.1_spec-1.0.0.Final.jar",
		"jcip-annotations-1.0.0.jar",
		"jcl-over-slf4j-1.7.6.jar",
		"jcommander-1.48.jar",
		"jcommon-1.0.23.jar",
		"jdom-1.0.jar",
		"jersey-client-1.19.1.jar",
		"jersey-core-1.19.1.jar",
		"jersey-multipart-1.19.1.jar",
		"jettison-1.2.jar",
		"jfreechart-1.0.19.jar",
		"jna-5.15.0.jar",
		"jna-platform-5.15.0.jar",
		"joda-time-2.4.jar",
		"jose4j-0.9.4.jar",
		"jsinterop-annotations-2.0.0.jar",
		"json-20140107.jar",
		"jsoup-1.15.3.jar",
		"jsr311-api-1.1.1.jar",
		"license-checker-1.13.3.jar",
		"log4j-1.2.17.jar",
		"lucene-analyzers-common-4.5.1.jar",
		"lucene-core-4.5.1.jar",
		"lucene-queries-4.5.1.jar",
		"lucene-queryparser-4.5.1.jar",
		"lucene-sandbox-4.5.1.jar",
		"migbase64-2.2.jar",
		"mime-util-2.1.3.jar",
		"mimepull-1.9.3.jar",
		"nimbus-jose-jwt-9.37.3.jar",
		"okhttp-2.0.0.jar",
		"okio-1.0.0.jar",
		"olap4j-0.9.7.309-JS-3.jar",
		"ooxml-schemas-1.1.jar",
		"open-8.5.0.4.jar",
		"org.apache.oltu.oauth2.client-1.0.2.jar",
		"org.apache.oltu.oauth2.common-1.0.2.jar",
		"oshi-core-6.6.5.jar",
		"pdfbox-2.0.4.jar",
		"poi-3.17.jar",
		"poi-ooxml-3.17.jar",
		"poi-ooxml-schemas-3.17.jar",
		"poi-scratchpad-3.17.jar",
		"re2j-1.6.jar",
		"sac-1.3.jar",
		"sias-docusign-esign-java-3.6.0.2.jar",
		"slf4j-api-1.7.16.jar",
		"slf4j-log4j12-1.7.16.jar",
		"snmp-6.1.jar",
		"specs-asic-manifest-6.0.jar",
		"specs-jades-6.0.jar",
		"specs-jws-6.0.jar",
		"specs-trusted-list-6.0.jar",
		"specs-validation-report-6.0.jar",
		"specs-xades-6.0.jar",
		"specs-xmldsig-6.0.jar",
		"spring-aop-4.2.3.RELEASE.jar",
		"spring-batch-admin-manager-1.3.1.RELEASE.jar",
		"spring-batch-admin-resources-1.3.1.RELEASE.jar",
		"spring-batch-core-3.0.8.RELEASE.jar",
		"spring-batch-infrastructure-3.0.8.RELEASE.jar",
		"spring-batch-integration-1.3.1.RELEASE.jar",
		"spring-beans-4.2.3.RELEASE.jar",
		"spring-context-4.2.3.RELEASE.jar",
		"spring-context-support-4.2.3.RELEASE.jar",
		"spring-core-4.2.3.RELEASE.jar",
		"spring-expression-4.2.3.RELEASE.jar",
		"spring-integration-core-3.0.2.RELEASE.jar",
		"spring-integration-file-3.0.2.RELEASE.jar",
		"spring-integration-http-3.0.2.RELEASE.jar",
		"spring-integration-jmx-3.0.2.RELEASE.jar",
		"spring-jdbc-4.2.3.RELEASE.jar",
		"spring-ldap-core-2.0.2.RELEASE.jar",
		"spring-orm-4.2.3.RELEASE.jar",
		"spring-oxm-4.2.3.RELEASE.jar",
		"spring-retry-1.0.2.RELEASE.jar",
		"spring-security-core-4.1.0.RELEASE.jar",
		"spring-security-crypto-4.1.0.RELEASE.jar",
		"spring-security-ldap-4.1.0.RELEASE.jar",
		"spring-tx-4.2.3.RELEASE.jar",
		"spring-web-4.2.3.RELEASE.jar",
		"spring-webmvc-4.2.3.RELEASE.jar",
		"stax-1.2.0.jar",
		"stax-api-1.0-2.jar",
		"stax-api-1.0.1.jar",
		"stax-utils-20040917.jar",
		"stax2-api-4.2.1.jar",
		"swagger-annotations-1.5.8.jar",
		"tagsoup-0.9.7.jar",
		"txw2-3.0.2.jar",
		"utl_encrypt-1.0.0.jar",
		"utl_encrypt-1.1.0.jar",
		"utl_encryptDecrypt-1.0.0.jar",
		"utl_encryptDecrypt-1.1.0.jar",
		"utl_signaturaDigital-1.0.0.jar",
		"vaadin-charts-4.2.0.jar",
		"vaadin-client-8.28.0.jar",
		"vaadin-compatibility-client-8.28.0.jar",
		"vaadin-compatibility-client-compiled-8.28.0.jar",
		"vaadin-compatibility-server-8.28.0.jar",
		"vaadin-compatibility-shared-8.28.0.jar",
		"vaadin-compatibility-themes-8.28.0.jar",
		"vaadin-push-8.28.0.jar",
		"vaadin-sass-compiler-0.9.13.jar",
		"vaadin-server-8.28.0.jar",
		"vaadin-shared-8.28.0.jar",
		"vaadin-slf4j-jdk14-1.6.1.jar",
		"vaadin-spreadsheet-2.1.1.jar",
		"vaadin-spring-3.2.1.jar",
		"vaadin-themes-8.28.0.jar",
		"validation-api-1.0.0.GA-sources.jar",
		"validation-api-1.0.0.GA.jar",
		"validation-policy-6.0.jar",
		"valnif-2.0.1.jar",
		"woodstox-core-6.5.1.jar",
		"xalan-2.7.0.jar",
		"xercesImpl-2.6.2.jar",
		"xml-apis-1.3.02.jar",
		"xml-apis-ext-1.3.04.jar",
		"xmlbeans-2.6.0.jar",
		"xmlgraphics-commons-2.1.jar",
		"xmlParserAPIs-2.6.2.jar",
		"xmlpull-1.1.3.1.jar",
		"xmlsec-3.0.3.jar",
		"xom-1.0b3.jar",
		"xpp3_min-1.1.4c.jar",
		"xstream-1.4.9.jar",
		"zip4j-2.11.5.jar",
		"ZSDK_API-2.14.jar",
		"ZSDK_CARD_API-2.14.jar" };
}